name: Build
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os:
          - label: Linux
            image: ubuntu-latest
          - label: macOS
            image: macos-12

    name: ${{ matrix.os.label }}
    runs-on: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@e1f2e54ff90b012560f19481e250bb7d909f3acd

      - name: Enable Binary Cache
        uses: cachix/cachix-action@v12
        with:
          name: colmena
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Colmena
        run: nix build -L

      - name: Build and install Colmena with flake-compat
        run: nix-env -if default.nix

      - name: Build manual
        run: nix build .#manual -L
