name: Linters

on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v15

      - name: Enable binary cache (optional)
        uses: cachix/cachix-action@v10
        with:
          name: colmena
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check EditorConfig
        run: nix-shell --run "editorconfig-checker"

      - name: Check flake8
        run: nix-shell --run "flake8 manual/preprocess.py"
