name: Linters

on:
  pull_request:
  push:
jobs:
  linters:
    name: Linters

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@e1f2e54ff90b012560f19481e250bb7d909f3acd

      - name: Enable binary cache
        uses: cachix/cachix-action@v12
        with:
          name: colmena
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check EditorConfig
        run: nix-shell --run "editorconfig-checker"

      - name: Check flake8
        run: nix-shell --run "flake8 manual/preprocess.py"

      - name: Check rustfmt
        run: nix-shell --run "cargo fmt --check"
